import Head from 'next/head'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta keyword="nextjs, hunting coder blog, javascript" />
      </Head>
      <Navbar pageValue={0} />
      <div className={styles.heroImg}>
        <img src="/homeImg.jpg" alt="home" className={styles.img} />
        <h1 className={styles.title}>
          {"<Hunting Coder />"}
        </h1>
      </div>
      <main className={styles.main}>

        <p className={styles.description}>
          {`"A blog for a hunting coder by a hunting coder"`}
        </p>
        <div className="blogs">
          <h3><u>Popular Blogs</u></h3>
          <div className="blogItem">
            <h5>How to learn JavaScript in 2022?</h5>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h5>How to learn JavaScript in 2022?</h5>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
          <div className="blogItem">
            <h5>How to learn JavaScript in 2022?</h5>
            <p>JavaScript is the language used to design logic for the web</p>
          </div>
        </div>
      </main>
    </div>
  )
}
